### PR TITLE
Fix: Missing language constant

### PR DESCRIPTION
**Pull request by billtomczak**
Re createed from PR #223

### CODE REVIEW

**Comment by billtomczak** [comment]
@Kostelano - Could you tell me where you were seeing the missing language constant in the backend? I'm not seeing a problem without applying your changes.

**Comment by Kostelano** [comment]
Good day!
The column on the right during file creation / editing.
https://ibb.co/n8JzVnV

**Comment by billtomczak** [comment]
Okay, that's what I thought. I see what's going on now. The fix will be a bit more complicated than this PR. But it will be corrected in the next version. Thank you for the help!

**Comment by billtomczak** [comment]
Replaced by
7290ad4aded01dd48b64c83dfac0672149c11ca7
OSTraining/OSDownloads-Pro@ecf32763da0a40b6df6c20536f90d83abb22a5ec

**Pull request closed without merging**
