### PR TITLE
Use fully qualified class for JHtml

### PR DESCRIPTION
**Pull request by nicksavov**
Fixes https://www.alledia.com/forum/osdownloads/277-error-jhtml-not-found/#1688

### CODE REVIEW

**Comment by nicksavov** [comment]
@andergmartins , we might need to release another version of OSDownloads with this fix. We've had two reports so far for it.

**Comment by nicksavov** [comment]
One more report.

**Comment by andergmartins** [comment]
@nicksavov thank you. We will have a release this week.

**Comment by nicksavov** [comment]
Thanks Anderson!

**Comment by nicksavov** [comment]
btw, the reports are getting more frequent.

**Comment by andergmartins** [comment]
Just released https://github.com/OSTraining/OSDownloads/releases/tag/v1.4.3

**Comment by nicksavov** [comment]
Thanks Anderson!

**Pull request merged**
